# Generated by Django 5.2.6 on 2026-07-16 06:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('skill_suggestion', '0001_initial'),
    ]

    operations = [
    ]
